override_fos_user_registration_register:
  path: /register.{_format}
  defaults: { _controller: UserBundle:Registration:register, _format: html }

fos_user_registration_check_email:
  path: /check-email
  defaults: { _controller: FOSUserBundle:Registration:checkEmail }

fos_user_registration_confirm:
  path: /confirm/{token}
  defaults: { _controller: FOSUserBundle:Registration:confirm }
  methods: [GET]

fos_user_registration_confirmed:
  path: /confirmed
  defaults: { _controller: FOSUserBundle:Registration:confirmed }
  methods: [GET]
