fos_user_security_login:
  path: /login.{_format}
  defaults: { _controller: UserBundle:Security:login, _format: html }

fos_user_security_check:
  path: /login_check
  defaults: { _controller: FOSUserBundle:Security:check}

fos_user_security_logout:
  path: /logout
  defaults: { _controller: FOSUserBundle:Security:logout }
