#app:
#    resource: "@PigaNgBaseBundle/Controller/"
#    type:     annotation

_front:
    resource: routings/front.yml

_fos_user:
    resource: routings/fos_user.yml

_fos_js:
    resource: routings/fos_js.yml
