homepage:
    resource: "@AppBundle/Resources/config/routing/homepage.yml"
    prefix:   /

rest:
    resource: "@AppBundle/Resources/config/routing/rest.yml"
    prefix:   /

angular:
    resource: "@AppBundle/Resources/config/routing/angular.yml"
    prefix:   /

